---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${CERT_NAME}
  namespace: ${NAMESPACE}
spec:
  secretName: ${CERT_NAME}-secret
  dnsNames:
  - ${DNS_NAME}
  issuerRef:
    name: my-ca-issuer
    kind: Issuer
    group: cert-manager.io
