name: Test nested
description: > 
  Action for testing purposes with nested test action


  Example:

  ```
  
  - name: Test nested
    uses: midokura/gha-devops/test-nested@main
    with:
      testString: Helo nested! 
  ```

inputs:
  testString:
    description: String for testing
    required: true

runs:
  using: composite
  steps:
    - name: Test nested
      uses: midokura/gha-devops/test@main
      with:
          testString: ${{ inputs.testString }}
