name: CI - Force renovate to inspect and upgrade relevant dependencies

on:
  push:
    branches:
      - main  
    paths:
      - .github/workflows/update-helmchart-dependencies.yaml
      - .github/workflows/ci-update-helmchart-deps.yaml
      - .github/chart-renovate.json5
  pull_request:
      paths:
      - .github/workflows/update-helmchart-dependencies.yaml
      - .github/workflows/ci-update-helmchart-deps.yaml
      - .github/chart-renovate.json5

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Action lint
      run: |
        go install github.com/rhysd/actionlint/cmd/actionlint@latest
        actionlint .github/workflows/update-helmchart-dependencies.yaml
