name: CI - Force renovate to inspect and upgrade relevant dependencies

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-helmchart-dependencies.yaml
      - .github/workflows/ci-update-helmchart-deps.yaml
      - .github/chart-renovate.json5
  pull_request:
    paths:
      - .github/workflows/update-helmchart-dependencies.yaml
      - .github/workflows/ci-update-helmchart-deps.yaml
      - .github/chart-renovate.json5

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Action lint
      uses: raven-actions/actionlint@v2
      with: 
        files: '.github/workflows/update-helmchart-dependencies.yaml'
    - name: Validate renovate config
      uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
      with: 
        config_file_path: .github/chart-renovate.json5
