name: GitHub Actions lint

on:
  workflow_dispatch:
  pull_request:

jobs:

  lint:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.5'
      - run: | 
          go version
          go install github.com/rhysd/actionlint/cmd/actionlint@latest
          actionlint    
