name: Self signed CA init
description: >
  Action for setting up a self signed CA authority. Requires Kubernetes running


  Example:

  ```

  - name: Self signed CA init
    uses: midokura/gha-devops/selfsigned-ca-init@main
      with:
        namespace: 'my-namespace'

  ```

inputs:
  cert_dir:
    description: DockerHub registry username
    required: false
    default: ''
  namespace:
    description: Namespace where certificates will be created
    required: default
    default: default

runs:
  using: composite
  steps:
    - name: Create CA
      shell: bash
      run: | 
        envsubst < ${{ github.action_path }}/selfsigned-ca.yaml | kubectl apply -f -
        until kubectl get secret -n "${NAMESPACE}" root-ca-secret; do
          echo Waiting for root-ca cert...
          sleep 2
        done
        if [ "${CERT_DIR}" != '' ]; then
          mkdir -p "${CERT_DIR}"
          for FILE in ca.crt tls.crt tls.key; do
            kubectl get secrets -n "${NAMESPACE}" root-ca-secret -o json | jq -r '.data."'${FILE}'"' > "${CERT_DIR}/${FILE}"
          done
          ls -l "${CERT_DIR}"
        fi
      env:
        NAMESPACE: ${{ inputs.namespace }}
        CERT_DIR: ${{ inputs.cert_dir }}
